---
deployment:
  tasks:
    # Установка Node.js окружения
    - export DEPLOYPATH=/home/intentionb/public_html/
    - export NODE_VERSION=18
    - export PATH=/opt/cpanel/ea-nodejs18/bin:/opt/cpanel/node/bin:$PATH

    # Копируем файлы в директорию развертывания
    - /bin/cp -R . $DEPLOYPATH

    # Переходим в директорию проекта
    - cd $DEPLOYPATH

    # Проверяем доступность Node.js и npm
    - which node
    - which npm
    - node --version
    - npm --version

    # Очищаем npm cache для избежания проблем
    - npm cache clean --force

    # Устанавливаем зависимости с увеличенным timeout
    - npm install --timeout=600000 --no-audit --no-fund

    # Собираем проект для продакшена
    - npm run build

    # Проверяем что папка dist создалась
    - ls -la dist/

    # Копируем собранные файлы в корень public_html
    - /bin/cp -R dist/* ./

    # Создаем .htaccess для SPA маршрутизации
    - echo "Options -MultiViews" > .htaccess
    - echo "RewriteEngine On" >> .htaccess
    - echo "RewriteCond %{REQUEST_FILENAME} !-f" >> .htaccess
    - echo "RewriteRule ^ index.html [QSA,L]" >> .htaccess

    # Опционально: удаляем только node_modules для экономии места
    # - rm -rf node_modules
