---
deployment:
  tasks:
    # Установка переменных окружения
    - export DEPLOYPATH=/home/intentionb/public_html/
    - export PATH=/opt/cpanel/ea-nodejs18/bin:/opt/cpanel/node/bin:/usr/local/bin:$PATH

    # Копируем файлы в директорию развертывания
    - /bin/cp -R . $DEPLOYPATH

    # Переходим в директорию проекта
    - cd $DEPLOYPATH

    # Устанавливаем зависимости
    - npm install --production=false --no-audit --no-fund

    # Собираем проект
    - npm run build

    # Копируем файлы из dist в корень и ПЕРЕЗАПИСЫВАЕМ существующие
    - /bin/cp -rf dist/* ./

    # Убеждаемся что index.html существует в корне
    - test -f ./index.html && echo "index.html найден в корне" || echo "ОШИБКА: index.html не найден!"

    # Создаем .htaccess для SPA маршрутизации
    - echo "DirectoryIndex index.html" > .htaccess
    - echo "Options -MultiViews" >> .htaccess
    - echo "RewriteEngine On" >> .htaccess
    - echo "RewriteCond %{REQUEST_FILENAME} !-f" >> .htaccess
    - echo "RewriteCond %{REQUEST_FILENAME} !-d" >> .htaccess
    - echo "RewriteRule ^ index.html [QSA,L]" >> .htaccess

    # Устанавливаем правильные права доступа
    - chmod 644 index.html
    - chmod 644 .htaccess

    # Удаляем node_modules для экономии места
    - rm -rf node_modules
